### ISSUE TITLE
FAB for composing mail

### ISSUE THREAD

**Issue by sbruder** [scoute-dich/K9-MailClient#10]
May it be possible to add an floating action button for composing a new mail to the main inbox view to allow faster interaction?

**Comment by scoute-dich** [comment]
I don't add new features. I just themed k9. If you want this feature please open an issue at the repo of original k9.

I also would like this and looked a bit in the code today, but I found no possibility. :-(

**Comment by J-Jamet** [comment]
Hi, this issue is closed but I have a question.
If I develop this features with a FAB, will you accept the pull request?

**Comment by scoute-dich** [comment]
Yes, of course.
