### ISSUE TITLE
Expose hard coded values

### ISSUE THREAD

**Issue by Primokorn** [scoute-dich/K9-MailClient#2]
Hi,
### Expected behavior
Please avoid color codes into layout folders. CMTE/Substratum can't properly theme apps if colors are located in those folders.
Please move the text color below to values > colors.xml
`layout/actionbar_custom.xml:6:            <TextView android:textAppearance="?android:textAppearanceMedium" android:textColor="@android:color/primary_text_dark" android:ellipsize="start" android:id="@id/actionbar_title_first" android:layout_width="wrap_content" android:layout_height="wrap_content" android:maxLines="1" />`

### Actual behavior
Unable to modify the title in the action bar.

### Environment
K-9 Mail version: 5.114

Android version: 6.0.1

Thank you.

**Comment by scoute-dich** [comment]
Have I understand right:

Only move the color of the text in the actionbar to colors xml? Of so I will make it in the next days...

**Comment by Primokorn** [comment]
Exactly. I set a white background for the header so I'd like to switch to a dark color instead of `@android:color/primary_text_dark`.

**Comment by scoute-dich** [comment]
Is it done with the latest push from today?

**Comment by Primokorn** [comment]
I'll have a look this weekend.

**Comment by Primokorn** [comment]
I created 2 PRs to fix this theming issue.
Please check and let me know. Thanks.

**Comment by scoute-dich** [comment]
Merged. Please close the issue if it is solved. Should I release an updated apk on xda?

**Comment by Primokorn** [comment]
No hurry. It's fine to have these commits for the next beta release.
