### ISSUE TITLE
Don't mix tagging schemes

### ISSUE THREAD

**Issue by krt16s** [scoute-dich/K9-MailClient#22]
Former releases used `v` to prefix release tags, but looking at https://github.com/scoute-dich/K9-MailClient/releases this was dropped for the current release. Please state which scheme you are going to use for further tags.

If this was a mistake, please tag this release with `v` as well (in addition, so keep the old one, too). Thanks.

**Comment by scoute-dich** [comment]
That was indeed a mistake and not intended. I will fix out.

**Comment by scoute-dich** [comment]
Thanks for telling me.
