### ISSUE TITLE
Publish the app on F-Droid & Play Store

### ISSUE THREAD

**Issue by uncertainquark** [scoute-dich/K9-MailClient#5]
Title says it all.

**Comment by scoute-dich** [comment]
I don't have an developer account (since I don't have a credit card), so I can't publish apps on Play Store. I only add apps to F-Droid, which are "my own". Anyway if you want the app to be published on F-Droid, you can create a topic here: https://f-droid.org/forums/forum/submission-queue/

**Comment by dkanada** [comment]
I would love to submit this app and your material fork of MuPDF to F-Droid, are you planning on updating these two in the future as their main forks are updated? If not I will include a disclaimer in the description that these are unmaintained. Also, it might also be a good idea to change the app names so there is no confustion, maybe something like K-9 Material and MuMaterial or something, let me know if you think that is a good idea.

**Comment by scoute-dich** [comment]
**K9 fork:**
Yes I will update this regularly. I already changed the name.

**MuPDF:**
I'm not able to build MuPDF from source. So I have prebuild libraries in my source. I don't know if this is possible in F-Droid. I will also not update MuPDF to the latest version. I use it for personal use and made some changes (own file explorer, menu in the pdf view) so that my fork works together with my app PDF Creator.

If you want you can give it a try. If there are any problems with publishing on F-Droid, which I can solve, I#m willingly to help, so just report.

Regards
Gaukler Faun

**Comment by dkanada** [comment]
Just added a submission request [here](https://gitlab.com/fdroid/rfp/issues/68) for K9. I will look at MuPDF to see if anything can be done to get it working and let you know if I have any issues, thanks for letting me add them to F-Droid.

**Comment by scoute-dich** [comment]
Ok, let's see ...

**Comment by krt16s** [comment]
@scoute-dich: Could you keep your tags updated and in-sync with the versionname/code (so not having an arbitrary release counter that is not reflected in the code)?

**Comment by haverholm** [comment]
Aaand it's up on F-droid :)

**Comment by scoute-dich** [comment]
@krt16s Is it so ok? If yes, I will close this issue.

**Comment by eternaltyro** [comment]
Yes, I just saw this under the "What's new?" section. This can be closed. By the way, cool app. Also please consider switching the PEP fork of K-9 to material too: https://pep.foundation/pep-software/index.html 

Thanks a lot for this.

**Comment by haverholm** [comment]
>please consider switching the PEP fork of K-9 to material too

YES!

**Comment by Flippylosaurus** [comment]
I can get the app pushed on GP, @scoute-dich are you OK with that?

**Comment by uncertainquark** [comment]
Would be wonderful!

- Jatan
Typed on mobile, avoid typos.

**Comment by scoute-dich** [comment]
Yes. I think it's ok. Of course with the correct sources and the hint, that this is an unofficial app.

**Comment by Flippylosaurus** [comment]
https://play.google.com/store/apps/details?id=com.maartendekkers.cmapp

**Comment by scoute-dich** [comment]
Ok. Thanks.
