### ISSUE TITLE
Crash on message sign

### ISSUE THREAD

**Issue by conspacer** [scoute-dich/K9-MailClient#7]
Preface: This issue is happening on [LineageOS ](http://lineageos.org/) which is still experimental, so it may be an issue from the OS. I don't have a stock or Google Android phone, so just nuke this issue if you can't reproduce it. K-9 Material installed [from F-Droid](https://f-droid.org/repository/browse/?fdfilter=k9&fdid=com.fsck.k9.material).
Using OpenKeychain (also latest) installed from [F-Droid](https://f-droid.org/repository/browse/?fdfilter=openpgp&fdid=org.sufficientlysecure.keychain)

### Expected behavior
Ability to sign emails (using OpenKeychain) without encrypting.

### Actual behavior
K9 crashes repeatedly when tapping "Sign only mode"

### Steps to reproduce
1. Generate or import a GPG/PGP key OpenKeychain
2. Turn on "Sign only" in K9 Settings
3. Try to sign a message without encrypting

### Environment
K-9 Mail version: 5.205

Android version: LineageOS 14.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP (Dovecot server)

I have K9 official on the phone as well and it works as expected.

**Comment by scoute-dich** [comment]
I will update my fork to next version these days. Perhaps than it works. You can test and report after the update.

**Comment by scoute-dich** [comment]
I released a new update today. Perhaps you can test it and report.
Regards
Gaukler Faun

**Comment by conspacer** [comment]
@scoute-dich I will test and update in next few days. Tx

**Comment by meiser79** [comment]
Still crashes on version 5.207.2.

**Comment by scoute-dich** [comment]
Since I'm only a hobby developer, I don't have the skills to find a solution for this. Sorry.

**Comment by conspacer** [comment]
ok, nw thanks for the software :)
