### ISSUE TITLE
Two requests about design only.

### ISSUE THREAD

**Issue by bergentroll** [scoute-dich/K9-MailClient#9]
Hi!

Some time ago I made a puppy icon for k9. It was denied by devs of vanilla k9, but may be you'd like to include it at least as an option? It's not actually MD, but it rather flat=)
![banner](https://github.com/bergentroll/k-9/blob/material_canine/images/new_feature_graphic.png?raw=true)
![icon](https://github.com/bergentroll/k-9/blob/material_canine/images/K-9_material_512x512.png?raw=true)

Also I want you to know, I found your colours choice not fits well. I am totally dislike this "X-mass" red-n-green colour theme, and want to ask you to make ability to customize colours from the options list please.

**Comment by scoute-dich** [comment]
1. You are totally right. I removed the green.
2. I will stay with my icon, because it matches to my CM Theme and to my Substratum Theme.
